### ISSUE TITLE
undefined is not an object (evaluating 'RNProgressHUB.IsAndroid')

### ISSUE THREAD

**Issue by mealbarracin10** [frontendhot/react-native-progresshub#2]
i try integrated this module, because after install it show this error in emulator 

![captura de pantalla 2017-09-03 a la s 2 11 13 p m](https://user-images.githubusercontent.com/11824876/30005894-f27895e2-90b1-11e7-8ab0-59f143b2f15a.png)

**Comment by prscX** [comment]
Hi @mealbarracin10 

I am also getting this error, I think it is fixed in the master branch

Maintainers - @frontendhot, can you please release a version with the same

I hope it will be released on priority

**Comment by frontendhot** [comment]
@prscX @mealbarracin10 Sorry for the late reply. please use command `react-native link react-native-progresshub` or `rnpm link react-native-progresshub` to link library. it will work.

**Comment by DurioLab** [comment]
@prscX @mealbarracin10  Sorry for the late reply. update to 0.1.3 version and don't forget use command `react-native link react-native-progresshub` or `rnpm link react-native-progresshub` to link library. it will work.

**Comment by prscX** [comment]
Thanks a lot @frontendhot for publishing the new version with fix's
