### ISSUE TITLE
undefined is not an boject(evaluating 'RNProgressHUB.showSpinIndeterminate')

### ISSUE THREAD

**Issue by xuexiaoao** [frontendhot/react-native-progresshub#4]
![_20171204212610](https://user-images.githubusercontent.com/18185523/33555060-e901b05e-d939-11e7-8378-a131a4a5625d.png)

**Comment by JasonPan** [comment]
I am experiencing this issue as well on iOS.

**Comment by HHuiHao** [comment]
try: AndroidManifest.xml add android:allowBackup="true"
`    <application
           android:allowBackup="true"
            ...
    </application>`

**Comment by xuexiaoao** [comment]
thanks you

**Comment by LuuLinhSon** [comment]
HHuiHao : It do not word with me. hix
